version: "3.7"

services:
  app:
    container_name: elearning_api
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    environment: 
      - DB_HOST=database
      - DB_NAME=elearning
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - database
  
  front:
    container_name: elearning_front
    build:
      context: ./e-learning-front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./e-learning-front:/e-learning-front
    command: >
      npm start

  database:
    container_name: elearning_api_db
    image: postgres:10-alpine
    restart: always
    environment:
      - POSTGRES_DB=elearning
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  pgdata: