# Generated by Django 3.1.8 on 2021-05-01 23:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='content_readed', to=settings.AUTH_USER_MODEL),
        ),
    ]
