# Generated by Django 3.1.8 on 2021-05-01 23:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_content_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='students',
            new_name='already_seen',
        ),
        migrations.AddField(
            model_name='content',
            name='currently_viewing',
            field=models.ManyToManyField(blank=True, related_name='content_current', to=settings.AUTH_USER_MODEL),
        ),
    ]
