# Generated by Django 3.1.7 on 2021-03-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20210317_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='title',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.RemoveField(
            model_name='text',
            name='title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
