# Generated by Django 3.1.7 on 2021-03-18 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0014_auto_20210318_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='module',
        ),
        migrations.RemoveField(
            model_name='file',
            name='order',
        ),
        migrations.RemoveField(
            model_name='image',
            name='module',
        ),
        migrations.RemoveField(
            model_name='image',
            name='order',
        ),
        migrations.RemoveField(
            model_name='text',
            name='module',
        ),
        migrations.RemoveField(
            model_name='text',
            name='order',
        ),
        migrations.RemoveField(
            model_name='video',
            name='module',
        ),
        migrations.RemoveField(
            model_name='video',
            name='order',
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('text', 'file', 'image', 'video')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.module')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
