export const GET_COURSES_REQUEST = 'GET_COURSES_REQUEST';
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const GET_COURSES_FAIL = 'GET_COURSES_FAIL';

export const COURSE_DETAIL_REQUEST = 'COURSE_DETAIL_REQUEST';
export const COURSE_DETAIL_SUCCESS = 'COURSE_DETAIL_SUCCESS';
export const COURSE_DETAIL_FAIL = 'COURSE_DETAIL_FAIL';

export const GET_STUDENT_COURSES_REQUEST = 'GET_STUDENT_COURSES_REQUEST';
export const GET_STUDENT_COURSES_SUCCESS = 'GET_STUDENT_COURSES_SUCCESS';
export const GET_STUDENT_COURSES_FAIL = 'GET_STUDENT_COURSES_FAIL';

export const GET_MODULES_REQUEST = 'GET_MODULES_REQUEST';
export const GET_MODULES_SUCCESS = 'GET_MODULES_SUCCESS';
export const GET_MODULES_FAIL = 'GET_MODULES_FAIL';

export const GET_CONTENT_REQUEST = 'GET_CONTENT_REQUEST';
export const GET_CONTENT_SUCCESS = 'GET_CONTENT_SUCCESS';
export const GET_CONTENT_FAIL = 'GET_CONTENT_FAIL';


export const GET_SUBJECTS_REQUEST = 'GET_SUBJECTS_REQUEST';
export const GET_SUBJECTS_SUCCESS = 'GET_SUBJECTS_SUCCESS';
export const GET_SUBJECTS_FAIL = 'GET_SUBJECTS_FAIL';


export const ENROLL_COURSE_REQUEST = 'ENROLL_COURSE_REQUEST';
export const ENROLL_COURSE_SUCCESS = 'ENROLL_COURSE_SUCCESS';
export const ENROLL_COURSE_FAIL = 'ENROLL_COURSE_FAIL';

export const CLEAR_ERROR = "CLEAR_ERROR";
